# Generated by Django 5.2.4 on 2026-05-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_onboarded_user_onboarding_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding_step',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
